dist: bionic
language: java
sudo: required
jdk:
- openjdk11
services:
- docker
notifications:
  slack:
    secure: CfOon5xVIVFiUQYeE9kC7GUOwPr+igeWSemL0NcpcEmzxC/4CkFC5ediR3znosufNxsexSXuC3mzy+UTzIstpcsxVWXdYwvlsrZjw0KVYEKpMcWl6MiWj0UUrggZDoV2xjKvcd4gxDgG/criOfJGxJEEjjWw0r+ZNRSDUHdNR7u13v0M4Sw6UOgdkyWP9mumiPWeH4ShF6Q5aRdLnPzeHLZQ/pKg4RgvlW08Km1Hb7W+UW/mXSSrvfeZUP8L4UF4znI+iekvI/1fslt5uc9lLaFlMqreZj6IzFrJLYG9EF29HcO7g/g7SkyldYLAlma36DxwdzfxSLgdqI0V3uTFlxic9QoElLAWlGZ6Q7lw8rxy61yMWdFoGEbrg3VPWqd72v7BQ4SyOuXMNSgoPKQvnkuAHAf4MDlb5wZutXKoO069ruMQ7zDrOcPe3fhreJM7Jz9VupvmWiwpE0q5067FtEeUYTo0LdifjjLAnar9NypvAnQhMJv9KxvWq3+Qs0lSf5NY3+dpoIJsUN5zIrAqj01mDER8J6MIMMU0zR+68sqD1T9wQgYexNqczLmbrPQNCwF/nz/vulIBiow2AM+mXG5XIHwcySbW9X2xSyXGxBeWTb3vvfczrnnmGY931i52ElIz2GN9xrg5sfSz91AAZRHeiUtmdIqXE4hZlkREqa4=
  email: false

before_install:
- git clone https://github.com/SBRG/bigg_models_data
install:
- printf "FROM openjdk:11-slim\n\nCOPY ModelPolisher-1.7.jar /\nCOPY models /models\nCMD \"/bin/sh\"" > docker/java_docker/Dockerfile
- gradle lightJar && mv target/ModelPolisher-1.7.jar docker/java_docker && cp -r bigg_models_data/models docker/java_docker
before_script:
- docker-compose up --build -d
script:
- docker-compose run java java -jar /ModelPolisher-1.7.jar --input=/models/RECON1.xml --output=/models/out/RECON1.xml --annotate-with-bigg=true --add-adb-annotations=true --output-combine=true
- docker-compose run java java -jar /ModelPolisher-1.7.jar --input=/models/ecoli_core_model.xml --output=/models/out/ecoli_core_model.xml --annotate-with-bigg=true --add-adb-annotations=true --output-combine=true
- docker-compose run java java -jar /ModelPolisher-1.7.jar --input=/models/yeast_7.00.xml --output=/models/out/yeast_7.00.xml --annotate-with-bigg=true --add-adb-annotations=true --output-combine=true
after_script:
- ls -lish bigg_models_data/out
- docker-compose down
git:
  depth: 1
